#!/usr/bin/env php
<?php
require_once 'GoogleFontsFetch.php';

// googlefonts fetch
$fetch = new GoogleFontsFetch();

// 把要下载的google fronts的url地址放到这里, 然后执行  php fetch
$gfarr = array(
	"https://fonts.googleapis.com/css?family=Poppins:300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i",
	"https://fonts.googleapis.com/css?family=Open+Sans:400,400i,600,600i,700,700i&display=swap&subset=cyrillic-ext",
	"https://fonts.googleapis.com/css2?family=Barlow:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&display=swap",
);


if (count($gfarr) == 1) {
	$zipfile = $fetch->fetchFont($gfarr[0]);
} else {
	$zipfile = $fetch->fetchFontMulti($gfarr);
}

exit($zipfile);
